name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Allow manual trigger as well
  workflow_dispatch:

permissions:
  contents: write   # needed to push to gh-pages
  pages: write      # future-proof if using pages build
  id-token: write   # OIDC (not strictly required here but common for Pages)

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          # enable force_orphan to avoid history issues when first creating the branch
          force_orphan: true
          # optionally: cname: example.com (already handled by CNAME file)
          cname: harshdeepsingh.in
          enable_jekyll: false

