name: Build and Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        env:
          HUGO_ENV: production
        run: |
          hugo version
          hugo --minify

      - name: List generated files (debug)
        run: |
          echo "Top-level public/ listing:" && find public -maxdepth 2 -type f | head -n 50
          test -f public/index.html && echo "index.html size:" && wc -c public/index.html || echo "index.html missing"

      - name: Add .nojekyll
        run: touch public/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  # Custom domain should be configured in repository Settings > Pages
